core/urls.py
from django.urls import path
from .views import (HomeView,
                    CheckoutView,
                    ItemDetailView,
                    OrderSummaryView,
                    ProductListView,
                    add_to_cart,
                    remove_from_cart,
                    remove_single_item_from_cart,
                    AddCouponView,
                    PaymentView,
                    Nosotrosview,
                    CategoryItemListView)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='core-home'),
    path('nosotros/', Nosotrosview.as_view(), name='core-nosotros'),
    path('checkout/', CheckoutView.as_view(), name='core-checkout'),
    path('products/', CategoryItemListView.as_view(), name='core-products-category'),
    path('product/<slug>/', ItemDetailView.as_view(), name='core-product'),
    path('order-summary/', OrderSummaryView.as_view(), name='core-order-summary'),
    path('add-to-cart/<slug>/', add_to_cart, name='core-add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='core-add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='core-remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='core-remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='core-payment'),
]

jardineando_projecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("admin/", admin.site.urls),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField

# Create your models here.

CATEGORY_CHOICES = (
    ('A', 'Arboles'),
    ('AR', 'Arbustos'),
    ('M', 'Macetas'),
    ('S', 'Semillas'),
    ('H', 'Herramientas'),
)

LABEL_CHOICES = (
    ('S', 'success'),
    ('D', 'danger'),
    ('W', 'warning')
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    on_sale = models.BooleanField(default=False)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=2, blank=True, null=True)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(default='default.jpg', upload_to='productos')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:core-product", kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse("core:core-add-to-cart", kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse("core:core-remove-from-cart", kwargs={'slug': self.slug})

    def get_discount_pencentaje(self):
        return int(((self.price - self.discount_price) / self.price) * 100)

    @property
    def display_price(self):
        if self.on_sale and self.discount_price:
            return self.discount_price
        return self.price

    def save(self, *args, **kwargs):
        if self.on_sale:
                self.label = 'D'
        elif self.on_sale == False and self.label == 'D':
                self.label = None

        super().save(*args, **kwargs)



ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username





class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        if self.item.on_sale:
            return self.quantity * self.item.discount_price
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return (self.quantity * self.item.price) - self.get_total_discount_item_price()


    def get_final_price(self):
        if self.item.on_sale:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()




class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        if total < 0 :
            total = 0
        return total

    def get_total_number_of_items(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.quantity
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(Seleccione un pais...)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(Seleccione un pais...)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
  
    set_default_shipping = forms.BooleanField(required=False)

    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Cupón de descuento',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))


class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)

core/templates/core/navbar.html
{% load static %}
{% load cart_templates_tags %}
<!--INICIO NAVBAR VERSION CARPETA INICIAL-->

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">
            <table class="icomo-marca">
                <tr>
                    <td>
                        <img class="icono" src="{% static 'core/img/icono.png' %}" alt="Icono flor">
                    </td>
                    <td>
                        Jardineando
                    </td>
                </tr>
            </table>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:core-nosotros' %}">Nosotros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:core-products-category' %}">Todos los productos</a>
                </li>
                <li class="nav-item">
                    <a href="carrito.html" class="nav-link"><i class="bi bi-cart2"></i></a>
                </li>
            </ul>
            <div class="d-flex align-items-center">
                {% if request.user.is_authenticated %}
                <a href="{% url 'core:core-order-summary' %}" class="nav-link">
                    <span class="badge red z-depth-1 mr-1">{{ request.user|cart_item_count }}</span>
                    <i class="fas fa-shopping-cart" style="color: white;"></i>
                    <span class="clearfix d-none d-sm-inline-block">Carro</span>
                </a>

                <a href="">
                    <button type="button" class="btn btn-outline-light btn-dark">
                        Hola, {{ request.user.username }}.</button>
                </a>
                <a href="{% url 'account_logout' %}">
                    <button type="button" class="btn btn-outline-light btn-dark">Cerrar Sesión</button>
                </a>
                {% else %}
                <a href="{% url 'account_login' %}">
                    <button type="button" class="btn btn-outline-light btn-dark">Iniciar Sesión</button>
                </a>
                <a href="{% url 'account_signup' %}">
                    <button type="button" class="btn btn-outline-light btn-dark">Registrarse</button>
                </a>
                {% endif %}
            </div>

        </div>
    </div>
</nav>


<!--FIN DEL NAVBAR-->

core/templates/core/order_summary.html
{% extends "core/base.html" %}

{% load l10n %} <!-- Load the 'l10n' template tag library -->
{% load humanize %}
{% load custom_filters %}

{% block content %}
  <!-- Main layout -->
  <main>
    <div class="container">
      <div class="table-responsive text-nowrap">
        <h2>Resúmen de Ordenes</h2>
        <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Nombre del Producto</th>
              <th scope="col">Precio</th>
              <th scope="col">Cantidad</th>
              <th scope="col">Precio Total por Producto</th>
            </tr>
          </thead>
          <tbody>
            {% for order_item in object.items.all %}
            <tr>
              <th scope="row">{{ forloop.counter }}</th>
              <td><h6>{{ order_item.item.title }}</h6></td>
              <td><h6>${{ order_item.item.price|add_thousands_separator }}</h6></td>
              <td><h6>
                <a href="{% url 'core:core-remove-single-item-from-cart' order_item.item.slug %}"><i class="far fa-minus-square mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:core-add-to-cart' order_item.item.slug %}"><i class="far fa-plus-square ml-2"></i></a>
                </h6>
              </td>
              <td>
                {% if order_item.item.on_sale %}
                <h6>
                    ${{ order_item.get_total_discount_item_price|add_thousands_separator }}
                    <span class="badge badge-primary">Ahorras (${{ order_item.get_amount_saved|add_thousands_separator }})</span>
                </h6>
                {% else %}
                <h6>${{ order_item.get_total_item_price|add_thousands_separator }}</h6>
                {% endif %}
                <h6><a style="color: red" href="{% url 'core:core-remove-from-cart' order_item.item.slug %}">
                    <i class="fas fa-trash float-right"></i></a>
                </h6>
              </td>
            </tr>

            {% endfor %}
            <tr>
                <td colspan="4"><h6><b>Total de la compra:</b></h6></td>
                <td colspan="5"><h6><b>${{ object.get_total|add_thousands_separator }}</b></h6></td>
              </tr>
              <tr>
                <td colspan="5">
                  <div class="text-right">
                    <a href="{% url 'core:core-home' %}" class="btn btn-primary btn-md">Seguir Comprando</a>
                    <a href="{% url 'core:core-checkout' %}" class="btn btn-warning btn-md">Ir a pagar</a>
                  </div>
                </td>
              </tr>

          </tbody>
        </table>
      </div>
    </div>
  </main>

{% endblock content %}

core/templates/core/products.html
{% extends "core/base.html" %}

{% block content %}
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark bg-success-subtle lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand"> Categorías:</span>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#basicExampleNav2" aria-controls="basicExampleNav2" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav2">

            <!-- Links -->
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Todas
                <span class="sr-only">(actual)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Arboles</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Arbustos</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Herramientas</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Semillas</a>
            </li>
            </ul>
            <!-- Links -->

            <form class="form-inline">
            <div class="md-form my-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
            </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                    {% if item.label == 'S' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">Nuevo</span>
                    {% elif item.label == 'D' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">Oferta</span>
                    {% elif item.label == 'W' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">Top-Ventas</span>
                    {% endif %}

                  </strong>
                </h5>

                <h5 class="font-weight-bold green-text">
                  <strong>
                  {% if item.on_sale %}
                    <div class="product-price-container product-normal-price mt-3">
                      <dd class="product-price-type">Precio $<del>{{ item.price|floatformat:"0g" }}</del></dd>
                      <dt class="product-price product-price__line-thru"></dt>
                    </div>
                    <div class="product-price-container product-internet-price mt-2">
                      <dd class="product-price-type">Oferta ${{ item.discount_price|floatformat:"0g" }}</dd>
                      <dt class="product-price"></dt>
                    </div>
                    <div class="product-price-container product-price-discount mt-3">
                      <dd class="product-price-type">Descuento<span class="badge rounded-pill badge-danger ms-2">
                        {{ item.get_discount_pencentaje }}%
                      </span></dd>
                    </div>
                  {% else %}
                    <div class="product-price-container product-normal-price mt-3">
                      <dd class="product-price-type">Precio ${{ item.price|floatformat:"0g" }}</dd>
                      <dt class="product-price product-price__line-thru"></dt>
                    </div>
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow first-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First">
              <span aria-hidden="true">&laquo;&laquo;</span>
              <span class="sr-only">Primera</span>
            </a>
          </li>
          {% endif %}

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Anterior</span>
            </a>
          </li>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{ num }}
                <span class="sr-only">(actual)</span>
              </a>
            </li>
            {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
              <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
              </li>
            {% elif num == page_obj.number|add:"-3" or num == page_obj.number|add:"3" %}
              <li class="page-item disabled">
                <span class="page-link">...</span>
              </li>
            {% endif %}
          {% endfor %}

          <!--Arrow right-->
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Siguiente</span>
            </a>
          </li>
          {% endif %}

          <!--Arrow last-->
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
              <span aria-hidden="true">&raquo;&raquo;</span>
              <span class="sr-only">Última</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->


    </div>
  </main>

{% endblock content %}

core/templates/core/products_category.html
{% extends "core/base.html" %}

{% load custom_filters %}

{% block content %}
  <main>
    <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark busqueda-producto mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand"> Categorías:</span>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#basicExampleNav2" aria-controls="basicExampleNav2" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav2">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:core-products-category' %}">Todas
              <span class="sr-only">(actual)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:core-products-category' %}?category=A" name="category">Arboles</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:core-products-category' %}?category=AR" name="category">Arbustos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:core-products-category' %}?category=M" name="category">Macetas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:core-products-category' %}?category=S" name="category">Semillas</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'core:core-products-category' %}?category=H" name="category">Herramientas</a>
          </li>
        </ul>
        <!-- Links -->

        <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'core:core-products-category' %}">
          <div class="input-group">
            <input class="form-control bg-success-subtle lighten-3 text-white  mr-sm-2 filtrar-producto" type="text" name="search" placeholder="¿Qué busca?" aria-label="Search">
            <div class="input-group-append btn-buscar ">
              <button class="btn btn-outline-white my-2 my-sm-0" type="submit">Buscar</button>
            </div>
          </div>
        </form>
      </div>
      <!-- Collapsible content -->
    </nav>
    <!--/.Navbar-->


      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <div class="card">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" {% endcomment %}
                <img src="{{ item.image.url }}" class="card-img-top">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <div class="card-body text-center">
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                    {% if item.label == 'S' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">Nuevo</span>
                    {% elif item.label == 'D' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">Oferta</span>
                    {% elif item.label == 'W' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">Top-Ventas</span>
                    {% endif %}

                  </strong>
                </h5>

                <h5 class="font-weight-bold green-text">
                  <strong>
                  {% if item.on_sale %}
                    <div class="product-price-container product-normal-price mt-3">
                      <dd class="product-price-type">Precio $<del>{{ item.price|add_thousands_separator }}</del></dd>
                      <dt class="product-price product-price__line-thru"></dt>
                    </div>
                    <div class="product-price-container product-internet-price mt-2">
                      <dd class="product-price-type">Oferta ${{ item.discount_price|add_thousands_separator }}</dd>
                      <dt class="product-price"></dt>
                    </div>
                    <div class="product-price-container product-price-discount mt-3">
                      <dd class="product-price-type">Descuento<span class="badge rounded-pill badge-danger ms-2">
                        {{ item.get_discount_pencentaje }}%
                      </span></dd>
                    </div>
                  {% else %}
                    <div class="product-price-container product-normal-price mt-3">
                      <dd class="product-price-type">Precio ${{ item.price|add_thousands_separator }}</dd>
                      <dt class="product-price product-price__line-thru"></dt>
                    </div>
                  {% endif %}
                  </strong>
                </h4>

              </div>

            </div>

          </div>
          {% endfor %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow first-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page=1" aria-label="First">
              <span aria-hidden="true">&laquo;&laquo;</span>
              <span class="sr-only">Primera</span>
            </a>
          </li>
          {% endif %}

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Anterior</span>
            </a>
          </li>
          {% endif %}

          {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
            <li class="page-item active">
              <a class="page-link" href="?page={{ page_obj.number }}">{{ num }}
                <span class="sr-only">(actual)</span>
              </a>
            </li>
            {% elif num > page_obj.number|add:"-3" and num < page_obj.number|add:"3" %}
              <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
              </li>
            {% elif num == page_obj.number|add:"-3" or num == page_obj.number|add:"3" %}
              <li class="page-item disabled">
                <span class="page-link">...</span>
              </li>
            {% endif %}
          {% endfor %}

          <!--Arrow right-->
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Siguiente</span>
            </a>
          </li>
          {% endif %}

          <!--Arrow last-->
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}" aria-label="Last">
              <span aria-hidden="true">&raquo;&raquo;</span>
              <span class="sr-only">Última</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->


    </div>
  </main>

{% endblock content %}